version: '3.9'

services:
  todoapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:80
    container_name: todoapp-container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
